// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace FileManagement.DataAccess
{
    public partial class Folder
    {
        public Folder()
        {
            Files = new HashSet<File>();
            InverseSubFolder = new HashSet<Folder>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string FolderName { get; set; }
        public int Size { get; set; }
        public int? SubFolderId { get; set; }
        public int AppUserId { get; set; }
        public bool IsActive { get; set; }

        [ForeignKey(nameof(AppUserId))]
        [InverseProperty(nameof(User.Folders))]
        public virtual User AppUser { get; set; }
        [ForeignKey(nameof(SubFolderId))]
        [InverseProperty(nameof(Folder.InverseSubFolder))]
        public virtual Folder SubFolder { get; set; }
        [InverseProperty(nameof(File.Folder))]
        public virtual ICollection<File> Files { get; set; }
        [InverseProperty(nameof(Folder.SubFolder))]
        public virtual ICollection<Folder> InverseSubFolder { get; set; }
    }
}