// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using FileManagement.DataAccess.Concrete.EntityFrameworkCore.Context;
using FileManagement.DataAccess;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace FileManagement.DataAccess.Concrete.EntityFrameworkCore.Context.Configurations
{
    public partial class FolderConfiguration : IEntityTypeConfiguration<Folder>
    {
        public void Configure(EntityTypeBuilder<Folder> entity)
        {
            entity.HasOne(d => d.AppUser)
                .WithMany(p => p.Folders)
                .HasForeignKey(d => d.AppUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Folders__AppUser__276EDEB3");

            entity.HasOne(d => d.SubFolder)
                .WithMany(p => p.InverseSubFolder)
                .HasForeignKey(d => d.SubFolderId)
                .HasConstraintName("FK__Folders__SubFold__267ABA7A");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Folder> entity);
    }
}
